"""empty message

Revision ID: 6ccddc24d8fa
Revises: 
Create Date: 2020-05-27 12:54:34.457250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccddc24d8fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('artists', sa.String(length=256), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('explicit', sa.Float(), nullable=True),
    sa.Column('track_id', sa.String(length=256), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
