"""empty message

Revision ID: a03cc211a75e
Revises: c742b65e9ba0
Create Date: 2020-05-27 17:10:00.705094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03cc211a75e'
down_revision = 'c742b65e9ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('artists', sa.String(length=256), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('explicit', sa.Float(), nullable=True),
    sa.Column('track_id', sa.String(length=256), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
