"""empty message

Revision ID: c742b65e9ba0
Revises: 6ccddc24d8fa
Create Date: 2020-05-27 16:52:31.755842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c742b65e9ba0'
down_revision = '6ccddc24d8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('mode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'mode')
    # ### end Alembic commands ###
